export const SEED_TREKS = [
  {
    _id: "seed-1",
    title: "Harishchandragad Trek",
    slug: "harishchandragad-trek",
    location: "Ahmednagar, Maharashtra",
    price: 1299,
    duration: "1 Day",
    elevation: "4,671 ft",
    difficulty: "Moderate" as const,
    distance: "8 km",
    bestSeason: "Oct - Feb",
    pickupPoint: "Kasara Railway Station",
    description:
      "Experience the iconic Konkan Kada cliff and ancient temples atop Harishchandragad. This moderate trek offers breathtaking views of the Sahyadri range and a glimpse into Maratha history.",
    shortDescription:
      "Iconic cliff views and ancient fort ruins in the heart of Sahyadri.",
    itinerary: [
      { time: "5:30 AM", activity: "Pickup from Kasara" },
      { time: "8:00 AM", activity: "Reach base village, breakfast" },
      { time: "9:00 AM", activity: "Start trek via Pachnai route" },
      { time: "12:00 PM", activity: "Reach Konkan Kada, explore fort" },
      { time: "2:00 PM", activity: "Lunch at top" },
      { time: "4:00 PM", activity: "Descend to base" },
      { time: "8:00 PM", activity: "Return to Mumbai" },
    ],
    included: [
      "Transport from pickup point",
      "Breakfast & Lunch",
      "Trek leader & guide",
      "First aid kit",
      "Entry permissions",
    ],
    excluded: ["Personal expenses", "Insurance", "Anything not mentioned"],
    thingsToCarry: [
      "Trekking shoes",
      "2L water",
      "Raincoat",
      "Cap & sunscreen",
      "Personal medicines",
      "Small backpack",
    ],
    gallery: [
      "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=80",
      "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
      "https://images.unsplash.com/photo-1454496522488-786a886969da?w=800&q=80",
    ],
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=80",
    mapEmbedUrl:
      "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3782.0!2d73.77!3d19.39!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zMTnCsDIzJzI0LjAiTiA3M8KwNDYnMTIuMCJF!5e0!3m2!1sen!2sin!4v1",
    availableSeats: 25,
    featured: true,
    availableDates: ["2025-07-24", "2025-07-25", "2025-07-26"],
    reviews: [
      {
        name: "Amit K.",
        rating: 5,
        comment: "Konkan Kada at sunrise was magical!",
        date: "2025-12-15",
      },
    ],
  },
  {
    _id: "seed-2",
    title: "Kalsubai Peak Trek",
    slug: "kalsubai-peak-trek",
    location: "Nashik, Maharashtra",
    price: 999,
    duration: "1 Day",
    elevation: "5,400 ft",
    difficulty: "Moderate" as const,
    distance: "6 km",
    bestSeason: "Oct - Mar",
    pickupPoint: "Kasara Railway Station",
    description:
      "Conquer the highest peak of Maharashtra! Kalsubai offers stunning panoramic views and a well-marked trail suitable for enthusiastic beginners.",
    shortDescription:
      "Maharashtra's highest peak with panoramic Sahyadri views.",
    itinerary: [
      { time: "4:00 AM", activity: "Pickup from Kasara" },
      { time: "7:00 AM", activity: "Reach Bari village" },
      { time: "7:30 AM", activity: "Start ascent" },
      { time: "11:00 AM", activity: "Summit Kalsubai" },
      { time: "1:00 PM", activity: "Descend & lunch" },
      { time: "7:00 PM", activity: "Return to Mumbai" },
    ],
    included: ["Transport", "Breakfast", "Trek guide", "Safety equipment"],
    excluded: ["Lunch (available at base)", "Personal gear"],
    thingsToCarry: ["Trekking shoes", "Water bottle", "Jacket", "Snacks"],
    gallery: [
      "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
      "https://images.unsplash.com/photo-1454496522488-786a886969da?w=800&q=80",
    ],
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    mapEmbedUrl:
      "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3782.0!2d73.73!3d19.60!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zMTnCsDM2JzAwLjAiTiA3M8KwNDMnNDguMCJF!5e0!3m2!1sen!2sin!4v1",
    availableSeats: 30,
    featured: true,
    availableDates: ["2025-07-25", "2025-07-26"],
    reviews: [],
  },
  {
    _id: "seed-3",
    title: "Rajmachi Fort Trek",
    slug: "rajmachi-fort-trek",
    location: "Lonavala, Maharashtra",
    price: 899,
    duration: "1 Day",
    elevation: "2,710 ft",
    difficulty: "Easy" as const,
    distance: "5 km",
    bestSeason: "Jun - Feb",
    pickupPoint: "Lonavala Railway Station",
    description:
      "A perfect beginner-friendly trek through lush green trails leading to the historic Rajmachi twin forts. Ideal for families and first-time trekkers.",
    shortDescription: "Easy fort trek near Lonavala, perfect for beginners.",
    itinerary: [
      { time: "6:00 AM", activity: "Meet at Lonavala station" },
      { time: "7:00 AM", activity: "Jeep ride to Udhewadi" },
      { time: "8:00 AM", activity: "Explore Shrivardhan & Manaranjan forts" },
      { time: "12:00 PM", activity: "Village lunch" },
      { time: "3:00 PM", activity: "Return journey" },
    ],
    included: ["Guide", "Jeep transport", "Lunch", "Entry fees"],
    excluded: ["Train tickets", "Personal expenses"],
    thingsToCarry: ["Comfortable shoes", "Water", "Hat", "Camera"],
    gallery: [
      "https://images.unsplash.com/photo-1454496522488-786a886969da?w=800&q=80",
    ],
    image: "https://images.unsplash.com/photo-1454496522488-786a886969da?w=800&q=80",
    mapEmbedUrl:
      "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3782.0!2d73.40!3d18.82!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zMTjCsDQ5JzEyLjAiTiA3M8KwMjQnMDAuMCJF!5e0!3m2!1sen!2sin!4v1",
    availableSeats: 20,
    featured: true,
    availableDates: ["2025-07-25", "2025-07-26"],
    reviews: [],
  },
  {
    _id: "seed-4",
    title: "Lohagad Fort Monsoon Trek",
    slug: "lohagad-fort-monsoon-trek",
    location: "Lonavala, Maharashtra",
    price: 799,
    duration: "Half Day",
    elevation: "3,389 ft",
    difficulty: "Easy" as const,
    distance: "4 km",
    bestSeason: "Jun - Sep",
    pickupPoint: "Malavli Railway Station",
    description:
      "Walk through misty monsoon clouds to the majestic Lohagad Fort. Famous for its 'Vinchu Daata' scorpion tail structure.",
    shortDescription: "Monsoon magic at the iconic Lohagad Fort near Lonavala.",
    itinerary: [
      { time: "7:00 AM", activity: "Meet at Malavli" },
      { time: "7:30 AM", activity: "Trek to fort" },
      { time: "10:00 AM", activity: "Explore fort & Vinchu Daata" },
      { time: "12:00 PM", activity: "Descend & depart" },
    ],
    included: ["Trek leader", "First aid", "Snacks"],
    excluded: ["Transport", "Meals"],
    thingsToCarry: ["Raincoat", "Extra clothes", "Waterproof bag"],
    gallery: [
      "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800&q=80",
    ],
    image: "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800&q=80",
    mapEmbedUrl: "",
    availableSeats: 35,
    featured: false,
    availableDates: ["2025-07-24", "2025-07-26"],
    reviews: [],
  },
  {
    _id: "seed-5",
    title: "Sandhan Valley Camping",
    slug: "sandhan-valley-camping",
    location: "Ahmednagar, Maharashtra",
    price: 2499,
    duration: "2 Days",
    elevation: "4,200 ft",
    difficulty: "Hard" as const,
    distance: "12 km",
    bestSeason: "Oct - Feb",
    pickupPoint: "Kasara Railway Station",
    description:
      "The Grand Canyon of Maharashtra! Rappelling, valley crossing, and overnight camping under the stars.",
    shortDescription: "Valley rappelling and stargazing camping adventure.",
    itinerary: [
      { time: "Day 1 - 6 AM", activity: "Depart from Mumbai" },
      { time: "Day 1 - 12 PM", activity: "Reach Samrad, lunch" },
      { time: "Day 1 - 2 PM", activity: "Valley descent & rappelling" },
      { time: "Day 1 - 8 PM", activity: "Campfire & dinner" },
      { time: "Day 2 - 6 AM", activity: "Sunrise trek" },
      { time: "Day 2 - 2 PM", activity: "Return journey" },
    ],
    included: [
      "Transport",
      "All meals",
      "Camping gear",
      "Rappelling equipment",
      "Expert guides",
    ],
    excluded: ["Personal insurance", "Tips"],
    thingsToCarry: [
      "Head torch",
      "Sleeping bag liner",
      "Warm clothes",
      "Trekking shoes",
    ],
    gallery: [
      "https://images.unsplash.com/photo-1478131143081-80f7f84b84df?w=800&q=80",
    ],
    image: "https://images.unsplash.com/photo-1478131143081-80f7f84b84df?w=800&q=80",
    mapEmbedUrl: "",
    availableSeats: 15,
    featured: true,
    availableDates: ["2025-07-24", "2025-07-25"],
    reviews: [],
  },
  {
    _id: "seed-6",
    title: "Visapur Fort Trek",
    slug: "visapur-fort-trek",
    location: "Lonavala, Maharashtra",
    price: 849,
    duration: "1 Day",
    elevation: "3,556 ft",
    difficulty: "Moderate" as const,
    distance: "7 km",
    bestSeason: "Oct - Mar",
    pickupPoint: "Malavli Railway Station",
    description:
      "Explore the lesser-known twin of Lohagad with ancient caves, water cisterns, and panoramic views of the Western Ghats.",
    shortDescription: "Hidden gem fort trek with caves and water tanks.",
    itinerary: [
      { time: "6:30 AM", activity: "Meet at Malavli" },
      { time: "7:00 AM", activity: "Trek via Bhaje caves route" },
      { time: "11:00 AM", activity: "Fort exploration" },
      { time: "2:00 PM", activity: "Return" },
    ],
    included: ["Guide", "Breakfast", "Entry fees"],
    excluded: ["Transport to Malavli"],
    thingsToCarry: ["Shoes", "Water", "Snacks"],
    gallery: [
      "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=80",
    ],
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=80",
    mapEmbedUrl: "",
    availableSeats: 22,
    featured: false,
    availableDates: ["2025-07-25", "2025-07-26"],
    reviews: [],
  },
];
